"""
figures.py — generates Figs. 3-8 for the GKP SDC paper from sweep.py's output.

Fig. 1 (circuit) is unchanged from the original paper and not regenerated
here. Fig. 2 (Voronoi cells) is a one-off geometric diagram generated by
fig2_voronoi.py, not a sweep-data plot, so it's also not touched here.

Data source: results/all.npz (written by sweep.py) for the discrete-eta
plots (Figs. 3, 5, 6), and direct import of sweep.py's C_square/C_hex for
the continuous-eta threshold curves (Figs. 4, 7, 8), since all.npz only
carries the 5 reported eta values and Figs. 4/7/8 need a fine eta grid.

Run:
    python3 sweep.py      # writes results/all.npz (if not already done)
    python3 figures.py    # writes figures/fig3-fig8 .pdf and .png
"""
import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

from sweep import C_square, C_hex, TARGET

OUTDIR = "figures"
os.makedirs(OUTDIR, exist_ok=True)

plt.rcParams.update({
    "font.size": 11,
    "axes.labelsize": 12,
    "legend.fontsize": 9.5,
    "figure.dpi": 150,
})

ETA_LIST = [0.70, 0.80, 0.90, 0.95, 0.99]
LINESTYLES = {0.70: "-", 0.80: "--", 0.90: "-.", 0.95: ":", 0.99: (0, (3, 1, 1, 1))}
SQ_COLOR, HEX_COLOR = "#6a3d9a", "#e66101"

def save(fig, name):
    fig.savefig(f"{OUTDIR}/{name}.pdf", bbox_inches="tight")
    fig.savefig(f"{OUTDIR}/{name}.png", bbox_inches="tight", dpi=300)
    plt.close(fig)
    print(f"  saved {name}.pdf / .png")

def load_data():
    if not os.path.exists("results/all.npz"):
        raise FileNotFoundError(
            "results/all.npz not found -- run 'python3 sweep.py' first."
        )
    return np.load("results/all.npz")

def bisect_threshold(f, eta, lo=-5.0, hi=20.0, tol=1e-3):
    if f(lo, eta) >= TARGET:
        return lo
    if f(hi, eta) < TARGET:
        return None
    for _ in range(40):
        mid = (lo + hi) / 2
        if f(mid, eta) >= TARGET:
            hi = mid
        else:
            lo = mid
        if hi - lo < tol:
            break
    return hi

def Csq_wrap(s, eta):
    return C_square(s, eta)[0]

def Chex_wrap(s, eta):
    return C_hex(s, eta)[0]

# ─────────────────────────────────────────────────────────────
# Fig 3: SDC capacity vs squeezing, both lattices, 5 etas
# ─────────────────────────────────────────────────────────────
def fig3(data):
    print("Fig 3: capacity vs squeezing...")
    s_vals = data["s_vals"]
    eta_vals = list(data["eta_vals"])
    C_sq_grid = data["C_sq"]
    C_hex_grid = data["C_hex"]

    fig, ax = plt.subplots(figsize=(6, 5))
    for eta in ETA_LIST:
        i = eta_vals.index(eta)
        ax.plot(s_vals, C_sq_grid[i], color=SQ_COLOR, linestyle=LINESTYLES[eta], lw=1.4)
        ax.plot(s_vals, C_hex_grid[i], color=HEX_COLOR, linestyle=LINESTYLES[eta], lw=1.4)

    ax.axhline(TARGET, color="gray", linestyle=":", lw=1, alpha=0.8)
    ax.text(3.2, TARGET + 0.03, "1.5-bit target", fontsize=9, color="gray")

    color_handles = [Line2D([0], [0], color=SQ_COLOR, lw=1.6, label=r"$C_{\rm sq}$"),
                      Line2D([0], [0], color=HEX_COLOR, lw=1.6, label=r"$C_{\rm hex}$")]
    style_handles = [Line2D([0], [0], color="k", lw=1.2, linestyle=LINESTYLES[e], label=fr"$\eta={e}$")
                      for e in ETA_LIST]
    leg1 = ax.legend(handles=color_handles, loc="lower right", frameon=False)
    ax.add_artist(leg1)
    ax.legend(handles=style_handles, loc="upper left", frameon=False, ncol=1)

    ax.set_xlabel("Squeezing $s$ (dB)")
    ax.set_ylabel("SDC capacity (bits)")
    ax.set_xlim(s_vals.min(), s_vals.max())
    ax.set_ylim(0, 2.05)
    save(fig, "fig3_capacity_vs_squeezing")

# ─────────────────────────────────────────────────────────────
# Fig 4: threshold squeezing vs eta, both lattices (fine eta grid)
# ─────────────────────────────────────────────────────────────
def fine_threshold_curves(eta_grid):
    s_sq, s_hex = [], []
    for eta in eta_grid:
        s_sq.append(bisect_threshold(Csq_wrap, eta))
        s_hex.append(bisect_threshold(Chex_wrap, eta))
    return np.array(s_sq, dtype=float), np.array(s_hex, dtype=float)

def fig4(eta_grid, s_sq, s_hex):
    print("Fig 4: threshold squeezing vs eta...")
    fig, ax = plt.subplots(figsize=(6, 5))
    mask_sq = ~np.isnan(s_sq)
    mask_hex = ~np.isnan(s_hex)
    ax.plot(eta_grid[mask_sq], s_sq[mask_sq], color=SQ_COLOR, lw=2, label=r"square, $s^{\rm sq}_{\rm thresh}$")
    ax.plot(eta_grid[mask_hex], s_hex[mask_hex], color=HEX_COLOR, lw=2, label=r"hex, $s^{\rm hex}_{\rm thresh}$")

    both = mask_sq & mask_hex
    if both.any():
        ax.fill_between(eta_grid[both], s_hex[both], s_sq[both], color=HEX_COLOR, alpha=0.15)

    ax.set_xlabel(r"Transmissivity $\eta$")
    ax.set_ylabel(r"Threshold squeezing (dB) for $C \geq 1.5$ bits")
    ax.legend(frameon=False)
    ax.set_xlim(eta_grid.min(), eta_grid.max())
    save(fig, "fig4_threshold_vs_eta")

# ─────────────────────────────────────────────────────────────
# Fig 5: capacity comparison (log scale) at eta=0.90
# ─────────────────────────────────────────────────────────────
def fig5(data):
    print("Fig 5: capacity comparison at eta=0.90...")
    s_vals = data["s_vals"]
    eta_vals = list(data["eta_vals"])
    i = eta_vals.index(0.90)

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.semilogy(s_vals, data["C_EA"][i], color="teal", lw=1.6, label=r"$C_{\rm EA}$")
    ax.semilogy(s_vals, data["C_hol"][i], color="gray", lw=1.6, linestyle="--", label=r"$C_{\rm hol}$")
    ax.semilogy(s_vals, data["C_hex"][i], color=HEX_COLOR, lw=1.8, label=r"$C_{\rm hex}$")
    ax.semilogy(s_vals, data["C_sq"][i], color=SQ_COLOR, lw=1.8, label=r"$C_{\rm sq}$")
    ax.set_xlabel("Squeezing $s$ (dB)")
    ax.set_ylabel("Capacity (bits, log scale)")
    ax.legend(frameon=False)
    ax.set_xlim(s_vals.min(), s_vals.max())
    save(fig, "fig5_capacity_comparison")

# ─────────────────────────────────────────────────────────────
# Fig 6: error probabilities (log scale) at eta=0.90
# ─────────────────────────────────────────────────────────────
def fig6(data):
    print("Fig 6: error probabilities at eta=0.90...")
    s_vals = data["s_vals"]
    eta_vals = list(data["eta_vals"])
    i = eta_vals.index(0.90)

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.semilogy(s_vals, data["p_e"][i], color=SQ_COLOR, lw=1.8, label=r"$p_e^{\rm sq}$")
    ax.semilogy(s_vals, data["p_I"][i], color=HEX_COLOR, lw=1.8, linestyle="-", label=r"$p_I$ (hex center-type)")
    ax.semilogy(s_vals, data["p_X"][i], color=HEX_COLOR, lw=1.8, linestyle="--", label=r"$p_X$ (hex corner-type)")
    ax.set_xlabel("Squeezing $s$ (dB)")
    ax.set_ylabel("Error probability (log scale)")
    ax.legend(frameon=False)
    ax.set_xlim(s_vals.min(), s_vals.max())
    save(fig, "fig6_error_probabilities")

# ─────────────────────────────────────────────────────────────
# Fig 7: hexagonal advantage delta_s vs eta
# ─────────────────────────────────────────────────────────────
def fig7(eta_grid, s_sq, s_hex):
    print("Fig 7: hex advantage vs eta...")
    both = ~np.isnan(s_sq) & ~np.isnan(s_hex)
    delta_s = s_sq[both] - s_hex[both]
    eta_both = eta_grid[both]

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.plot(eta_both, delta_s, color="#1f4e79", lw=2)
    coding_gain = 10 * np.log10(2 / np.sqrt(3))
    ax.axhline(coding_gain, color="gray", linestyle=":", lw=1)
    ax.text(eta_both.min() + 0.01, coding_gain + 0.08,
            r"$10\log_{10}(2/\sqrt{3})$", fontsize=9, color="gray")
    ax.set_xlabel(r"Transmissivity $\eta$")
    ax.set_ylabel(r"$\delta s$ (dB)")
    save(fig, "fig7_hex_advantage")

# ─────────────────────────────────────────────────────────────
# Fig 8: hardware context
# ─────────────────────────────────────────────────────────────
def fig8(eta_grid, s_sq, s_hex):
    print("Fig 8: hardware context...")
    fig, ax = plt.subplots(figsize=(6, 5))
    mask_sq, mask_hex = ~np.isnan(s_sq), ~np.isnan(s_hex)
    ax.plot(eta_grid[mask_sq], s_sq[mask_sq], color=SQ_COLOR, lw=2, label="square")
    ax.plot(eta_grid[mask_hex], s_hex[mask_hex], color=HEX_COLOR, lw=2, label="hex")

    ax.axhline(7.8, color="k", linestyle="--", lw=1)
    ax.text(eta_grid.min() + 0.01, 7.8 + 0.15, "trapped-ion (7.8 dB) [22]", fontsize=8.5)

    ax.axhspan(9.9, 14.8, color="gray", alpha=0.15)
    ax.text(eta_grid.min() + 0.01, 12.0, "fault-tolerance threshold band [19,20]",
            fontsize=8.5, va="center")

    ax.set_xlabel(r"Transmissivity $\eta$")
    ax.set_ylabel("Squeezing (dB)")
    ax.legend(frameon=False, loc="upper right")
    save(fig, "fig8_hardware_context")

if __name__ == "__main__":
    data = load_data()
    fig3(data)
    eta_grid = np.round(np.arange(0.70, 0.991, 0.005), 4)
    s_sq, s_hex = fine_threshold_curves(eta_grid)
    fig4(eta_grid, s_sq, s_hex)
    fig5(data)
    fig6(data)
    fig7(eta_grid, s_sq, s_hex)
    fig8(eta_grid, s_sq, s_hex)
    print("\nAll figures regenerated in ./figures/")
